export const INSTRUMENT_ADAPTER_TOKENS = {
  ENGINE_SPESSA: 'spessa',
  ENGINE_SMPLR: 'smplr',
  ENGINE_SYNTH_FALLBACK: 'synthFallback',
  ENGINE_GUITAR_MODEL: 'guitarModel',

  DEFAULT_CHANNEL: 0,
  DEFAULT_VELOCITY: 0.8,
  DEFAULT_DURATION_SECONDS: 2.5,
  DEFAULT_RELEASE_SECONDS: 0.08,
  DEFAULT_BEND_RATIO: 1,
  DEFAULT_FILTER_FREQUENCY: 4200,
  DEFAULT_GAIN: 0.08,

  EVENT_READY: 'ready',
  EVENT_ERROR: 'error',
  EVENT_LOAD_PROGRESS: 'loadProgress',
} as const;

export type InstrumentEngineId =
  | typeof INSTRUMENT_ADAPTER_TOKENS.ENGINE_SPESSA
  | typeof INSTRUMENT_ADAPTER_TOKENS.ENGINE_SMPLR
  | typeof INSTRUMENT_ADAPTER_TOKENS.ENGINE_SYNTH_FALLBACK
  | typeof INSTRUMENT_ADAPTER_TOKENS.ENGINE_GUITAR_MODEL;
