export const KEYBOARD_TOKENS = {
  DIGIT_0: "Digit0", DIGIT_1: "Digit1", DIGIT_2: "Digit2", DIGIT_3: "Digit3",
  DIGIT_4: "Digit4", DIGIT_5: "Digit5", DIGIT_6: "Digit6", DIGIT_7: "Digit7",
  DIGIT_8: "Digit8", DIGIT_9: "Digit9",
  NUMPAD_0: "Numpad0", NUMPAD_1: "Numpad1", NUMPAD_2: "Numpad2", NUMPAD_3: "Numpad3",
  NUMPAD_4: "Numpad4", NUMPAD_5: "Numpad5", NUMPAD_6: "Numpad6", NUMPAD_7: "Numpad7",
  NUMPAD_8: "Numpad8", NUMPAD_9: "Numpad9",
  KEY_A: "KeyA", KEY_S: "KeyS", KEY_D: "KeyD", KEY_F: "KeyF", KEY_G: "KeyG",
  KEY_H: "KeyH", KEY_J: "KeyJ", KEY_K: "KeyK", KEY_L: "KeyL",
  KEY_Q: "KeyQ", KEY_W: "KeyW", KEY_E: "KeyE", KEY_R: "KeyR", KEY_T: "KeyT",
  KEY_Y: "KeyY", KEY_U: "KeyU", KEY_I: "KeyI", KEY_O: "KeyO", KEY_P: "KeyP",
  KEY_Z: "KeyZ", KEY_X: "KeyX", KEY_C: "KeyC", KEY_V: "KeyV", KEY_B: "KeyB",
  KEY_N: "KeyN", KEY_M: "KeyM",
  MINUS: "Minus", EQUAL: "Equal",
  BRACKET_LEFT: "BracketLeft", BRACKET_RIGHT: "BracketRight",
  SEMICOLON: "Semicolon", QUOTE: "Quote", BACKSLASH: "Backslash",
  COMMA: "Comma", PERIOD: "Period", SLASH: "Slash",
  SPACE: "Space", ENTER: "Enter",
  ARROW_DOWN: "ArrowDown", ARROW_UP: "ArrowUp", ARROW_LEFT: "ArrowLeft", ARROW_RIGHT: "ArrowRight",
  SHIFT_LEFT: "ShiftLeft", SHIFT_RIGHT: "ShiftRight",
  CTRL_LEFT: "ControlLeft", CTRL_RIGHT: "ControlRight",
  ALT_LEFT: "AltLeft", ALT_RIGHT: "AltRight",
  META_LEFT: "MetaLeft", META_RIGHT: "MetaRight",
  F1: "F1", F2: "F2", F3: "F3", F4: "F4", F5: "F5", F6: "F6", F7: "F7", F8: "F8",
  KEY_RAW_SHIFT: "Shift", KEY_RAW_CTRL: "Control", KEY_RAW_ALT: "Alt", KEY_RAW_META: "Meta",
  PLUS: "Plus",
};
